# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('badge_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('min_points', models.IntegerField(unique=True)),
                ('max_points', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('image_profile', models.ImageField(blank=True, upload_to='profile_images/')),
                ('address', models.TextField(blank=True, max_length=128)),
                ('key_activation', models.CharField(blank=True, max_length=40)),
                ('points_accumulated', models.IntegerField(default=0)),
                ('badge_acquired', models.CharField(default='beginner', max_length=32)),
                ('date_key_expiration', models.DateTimeField(auto_now_add=True)),
                ('user_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
